spring.application.name=website-route
server.port=${PORT:8080}
influxdb.url=${InfluxDb__Url:https://51h585.stackhero-network.com}
influxdb.token=${InfluxDb__Token:}
influxdb.bucket=${InfluxDb__Bucket:test-bucket}
influxdb.organization=${InfluxDb__Organization:organization}
influxdb.plane-id=${InfluxDb__PlaneId:test-plane}
