<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InfluxDB.Client" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebSiteRoute.Application\WebSiteRoute.Application.csproj" />
    <ProjectReference Include="..\WebSiteRoute.Domain\WebSiteRoute.Domain.csproj" />
  </ItemGroup>

</Project>
